# Generated by Django 3.0.7 on 2020-06-08 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='display name')),
                ('vle_course_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='VLE Course ID Number')),
                ('compulsory', models.BooleanField(default=False, verbose_name='compulsory')),
                ('commitment', models.CharField(blank=True, max_length=100, verbose_name='commitment')),
                ('credits', models.PositiveIntegerField(blank=True, null=True, verbose_name='credits')),
                ('weeks_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration in weeks')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display name')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='display name')),
                ('vle_course_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='VLE Course ID Number')),
                ('open_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='open date')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end (complete) date')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='close date')),
                ('master_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programmes.MasterCourse')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledCourseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='display name')),
                ('vle_group_id', models.CharField(db_index=True, max_length=100, verbose_name='VLE Group ID Number')),
                ('scheduled_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programmes.ScheduledCourse')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeCourse',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('programmes.programme',),
        ),
        migrations.CreateModel(
            name='ProgrammeStage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('programmes.programme',),
        ),
        migrations.CreateModel(
            name='UserProgramme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.Programme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'programme')},
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display name')),
                ('stage_order', models.PositiveIntegerField(verbose_name='Order')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.Programme')),
            ],
            options={
                'unique_together': {('programme', 'stage_order')},
            },
        ),
        migrations.CreateModel(
            name='ProgrammeMasterCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('master_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.MasterCourse')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.Programme')),
            ],
            options={
                'unique_together': {('programme', 'master_course')},
            },
        ),
    ]
